name: Update Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    # - uses: actions/checkout@v2
    #   with:
    #     path: stats
    #     repository: harunkurtdev/stats
    #     token: ${{ secrets.ACCESS_TOKEN }}
    
    # Push generated stats to GMahmoud
    - name: Get generated stats to profile repo
      run: |
        git config --global user.name "harunkurtdev"
        git config --global user.email "harunkurt.dev@gmail.com"  
        rm -rf generated
        cp -r stats/generated .
        rm stats -rf
        git add .
        git commit -m 'Update generated files' || echo
        git push
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}