name: Update Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *" # every day 5 hour later run
    #- cron: "*/10 * * * *" # every 10 minute
 
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v2
      
    - name: Checkout Stats Repository
      uses: actions/checkout@v2
      with:
        path: stats
        repository: harunkurtdev/harunkurtdev
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Update and Commit Stats
      run: |
        git config --global user.name "harunkurtdev"
        git config --global user.email "harunkurt.dev@gmail.com"  
        rm -rf generated
        git add .
        git commit -m 'Update generated files' || true
        cp -r stats/generated .
        rm -rf stats
        git add .
        git commit -m 'Update generated files' || true
        git push
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
